### ISSUE TITLE
Add a publisher to push generated schemas to different endpoints like s3, github.io etc.

### ISSUE THREAD

**Issue by dchakrav-github** [aws-cloudformation/aws-cloudformation-template-schema#15]

**Comment by PatMyron** [comment]
[Bundled updated schemas into the VSCode extension](https://github.com/aws-cloudformation/aws-cloudformation-template-schema/pull/45) and manually maintaining them [here](https://raw.githubusercontent.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/master/schema/all-spec.json) (https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues/32) due to automation difficulties described in similar https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues/3
