### ISSUE TITLE
Create a release pipeline to publish a built tool

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/aws-cloudformation-template-schema#3]
For customers who don't want to `git` we should add a Release artifact on our pipeline so they can just consume the tool without maven/Java/etc

**Comment by PatMyron** [comment]
think skipping all the way to [published schemas themselves](https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues/15) would make more sense than just the built tool

last couple dozen [Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) have [all been malformed](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pulls?q=is:pr+%22Template+Schema%22) and there have been enough [dependency issues](https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues?q=label:dependencies) recently that it has needed manual intervention anyway. [Bundled updated schemas into the VSCode extension](https://github.com/aws-cloudformation/aws-cloudformation-template-schema/pull/45) and manually maintaining them [here](https://raw.githubusercontent.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/master/schema/all-spec.json) (https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues/32) due to automation difficulties
